esphome:
  name: multi-switch
  friendly_name: multi-switch

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

substitutions:
  double_min:   10ms
  double_max: 180ms
  short_min:  50ms
  short_max: 2000ms
  long_min:  2001ms
  long_max:  10000ms
  delay: 100ms

event:
  - platform: template
    id: sw_1
    name: Switch 1
    device_class: button
    event_types:
      - idle
      - pressed_short
      - pressed_long
      - pressed_double

  - platform: template
    id: sw_2
    name: Switch 2
    device_class: button
    event_types:
      - idle
      - pressed_short
      - pressed_long
      - pressed_double

  - platform: template
    id: sw_3
    name: Switch 3
    device_class: button
    event_types:
      - idle
      - pressed_short
      - pressed_long
      - pressed_double

  - platform: template
    id: sw_4
    name: Switch 4
    device_class: button
    event_types:
      - idle
      - pressed_short
      - pressed_long
      - pressed_double

binary_sensor:
  # ====[ SWITCH 1 ]====
  - platform: gpio
    name: "sw_1"
    internal: true
    pin:
      number: GPIO32
      inverted: true
      mode:
        input: true
        pullup: true

    on_multi_click:
    - timing:
        - ON for 30ms to 1000ms
        - OFF for at most 200ms
        - ON for 30ms to 1000ms
        - OFF for at least 200ms
      then:
        - event.trigger:
            id: sw_1
            event_type: pressed_double
        - delay: ${delay}
        - event.trigger:
            id: sw_1
            event_type: idle
    - timing:
        - ON for 30ms to 1000ms
        - OFF for at least 400ms
      then:
        - event.trigger:
            id: sw_1
            event_type: pressed_short
        - delay: ${delay}
        - event.trigger:
            id: sw_1
            event_type: idle
    - timing:
        - ON for at least 1001ms
        - OFF for at least 400ms
      then:
        - event.trigger:
            id: sw_1
            event_type: pressed_long
        - delay: ${delay}
        - event.trigger:
            id: sw_1
            event_type: idle

  # ====[ SWITCH 2 ]====
  - platform: gpio
    name: "sw_2"
    internal: true
    pin:
      number: GPIO33
      inverted: true
      mode:
        input: true
        pullup: true

    on_multi_click:
    - timing:
        - ON for 30ms to 1000ms
        - OFF for at most 200ms
        - ON for 30ms to 1000ms
        - OFF for at least 200ms
      then:
        - event.trigger:
            id: sw_2
            event_type: pressed_double
        - delay: ${delay}
        - event.trigger:
            id: sw_2
            event_type: idle
    - timing:
        - ON for 30ms to 1000ms
        - OFF for at least 400ms
      then:
        - event.trigger:
            id: sw_2
            event_type: pressed_short
        - delay: ${delay}
        - event.trigger:
            id: sw_2
            event_type: idle
    - timing:
        - ON for at least 1001ms
        - OFF for at least 400ms
      then:
        - event.trigger:
            id: sw_2
            event_type: pressed_long
        - delay: ${delay}
        - event.trigger:
            id: sw_2
            event_type: idle

  # ====[ SWITCH 3 ]====
  - platform: gpio
    name: "sw_3"
    internal: true
    pin:
      number: GPIO25
      inverted: true
      mode:
        input: true
        pullup: true

    on_multi_click:
    - timing:
        - ON for 30ms to 1000ms
        - OFF for at most 200ms
        - ON for 30ms to 1000ms
        - OFF for at least 200ms
      then:
        - event.trigger:
            id: sw_3
            event_type: pressed_double
        - delay: ${delay}
        - event.trigger:
            id: sw_3
            event_type: idle
    - timing:
        - ON for 30ms to 1000ms
        - OFF for at least 400ms
      then:
        - event.trigger:
            id: sw_3
            event_type: pressed_short
        - delay: ${delay}
        - event.trigger:
            id: sw_3
            event_type: idle
    - timing:
        - ON for at least 1001ms
        - OFF for at least 400ms
      then:
        - event.trigger:
            id: sw_3
            event_type: pressed_long
        - delay: ${delay}
        - event.trigger:
            id: sw_3
            event_type: idle

  # ====[ SWITCH 4 ]====
  - platform: gpio
    name: "sw_4"
    internal: true
    pin:
      number: GPIO26
      inverted: true
      mode:
        input: true
        pullup: true

    on_multi_click:
    - timing:
        - ON for 30ms to 1000ms
        - OFF for at most 200ms
        - ON for 30ms to 1000ms
        - OFF for at least 200ms
      then:
        - event.trigger:
            id: sw_4
            event_type: pressed_double
        - delay: ${delay}
        - event.trigger:
            id: sw_4
            event_type: idle
    - timing:
        - ON for 30ms to 1000ms
        - OFF for at least 400ms
      then:
        - event.trigger:
            id: sw_4
            event_type: pressed_short
        - delay: ${delay}
        - event.trigger:
            id: sw_4
            event_type: idle
    - timing:
        - ON for at least 1001ms
        - OFF for at least 400ms
      then:
        - event.trigger:
            id: sw_4
            event_type: pressed_long
        - delay: ${delay}
        - event.trigger:
            id: sw_4
            event_type: idle